Repository softeerbootcamp-2nd/H1-MyCarDeepDive, pull requests merged in 2023-08, with the labels that each got.

#132 [FE] 색상 선택 UI 완성
  frontend/src/App.tsx
  frontend/src/Components/Header/Navigation/Item/index.tsx
  frontend/src/Components/Header/Navigation/index.tsx
  frontend/src/Components/Header/NavigationRadioGroup/NavigationRadioUnselected/index.tsx
  frontend/src/Components/Header/NavigationRadioGroup/index.tsx
  frontend/src/Components/Header/index.tsx
  frontend/src/Components/UnderLine/index.tsx
  frontend/src/Pages/ColorSelectionPage/Buttons/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Buttons/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/ChangePrice/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/ChangeTrim/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/CurrentTrim/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Explain/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/ModalContentsWrapper/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Title/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/TrimInfo/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorTitle/index.tsx
  frontend/src/Pages/ColorSelectionPage/ContentsWrapper/index.tsx
  frontend/src/Pages/ColorSelectionPage/Description/index.tsx
  frontend/src/Pages/ColorSelectionPage/DropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/index.tsx
  frontend/src/Pages/RecommendationPage/ResultPage/index.tsx
  frontend/src/Pages/RecommendationPage/index.tsx
  frontend/src/Pages/TrimSelectionPage/index.tsx
  frontend/src/assets/icon/check-circle-white.svg
  frontend/src/assets/icon/down-arrow.svg
  frontend/src/assets/image/exterior-abyss.png
  frontend/src/assets/image/exterior-creamy.png
  frontend/src/assets/image/exterior-gaia.png
  frontend/src/assets/image/exterior-graphite.png
  frontend/src/assets/image/exterior-moonlight.png
  frontend/src/assets/image/exterior-robust.png
  frontend/src/assets/image/exterior-shimmering.png
  frontend/src/assets/image/interior-black.png
  frontend/src/assets/image/interior-brown.png
  frontend/src/assets/image/interior-burgundy.png
  frontend/src/assets/image/interior-coolgray.png
  frontend/src/assets/image/interior-navy.png
  frontend/src/assets/image/interior-navy_warmgray.png
  frontend/src/assets/image/interior-onetone_balck.png
  frontend/src/assets/image/interior-premium_black.png
  frontend/src/assets/image/interior-quilted.png
  frontend/src/assets/image/interior-synthetic_black.png
  frontend/src/global/data.ts
  frontend/src/global/type.ts
Labels: 💡 Feature, 🌐 Frontend, 🖌 Design

#134 [BE] feat: sonarCloud 연동
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  build.gradle
Labels: 💡 Feature, 💯 Backend

#140 [BE] feat: 색상 선택 api 수정
  src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimExteriorColorRepository.java
  src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimInteriorColorRepository.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/ColorController.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
Labels: 💡 Feature, 💯 Backend

#141 [BE] refactor: dto 필드 명시적으로 변경
  src/main/java/com/h1/mycardeepdive/options/ui/dto/AdditionalOptionResponse.java
  src/main/java/com/h1/mycardeepdive/options/ui/dto/BasicOptionResponse.java
  src/main/java/com/h1/mycardeepdive/options/ui/dto/OptionCoordinatesResponse.java
  src/main/java/com/h1/mycardeepdive/options/ui/dto/PackageOptionResponse.java
Labels: 🏖 Common, 💯 Backend

#138 [FE] 전역 카스토어 환경 설정
  frontend/src/context/CarProvider/index.tsx
  frontend/src/context/CarProvider/type.ts
  frontend/src/context/QuestionProvider/index.tsx
  frontend/src/context/QuestionProvider/type.ts
  frontend/src/main.tsx
Labels: 💡 Feature, 🌐 Frontend

#143 [FE] useFetch & Suspense
  frontend/src/App.tsx
  frontend/src/Components/Loading/index.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/router/index.tsx
Labels: 🌐 Frontend

#144 [BE] feat: 패키지 옵션에 포함된 옵션 리스트 dto에 추가
  src/main/java/com/h1/mycardeepdive/options/mapper/OptionMapper.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/java/com/h1/mycardeepdive/options/ui/dto/PackageOptionResponse.java
  src/test/java/com/h1/mycardeepdive/options/ui/OptionsControllerTest.java
Labels: 🏖 Common, 💯 Backend

#147 [iOS] 공통 Alert 구현
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Presentation/Common/View/LeftAndRightButtonStackView.swift
  GetYa/GetYa/Presentation/Common/View/LeftAndRightButtonsView.swift
  GetYa/GetYa/Presentation/Common/View/OptionNameAndPriceView.swift
  GetYa/GetYa/Presentation/Common/View/OptionSummaryContentView.swift
  GetYa/GetYa/Presentation/Common/View/SettingAlertView.swift
  GetYa/GetYa/Presentation/Common/ViewController/AlertViewController.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/View/CustomOrQuoteSelectView.swift
  GetYa/GetYa/Util/Enum/AlertType.swift
  GetYa/GetYa/Util/Enum/Enum.swift
  GetYa/GetYa/Util/Enum/GetYaFont.swift
  GetYa/GetYa/Util/Extension/UIViewController+.swift
Labels:  iOS, 🖥 View

#152 [FE] deploy.yml 파일 루트로 이동
  .github/workflows/deploy.yml
Labels: 🌐 Frontend

#153 [FE] React Project V0.0.2
  .github/workflows/deploy.yml
Labels: 🌐 Frontend

#154 [FE] HOTFIX: fixed deploy.yml V0.0.1
  .github/workflows/deploy.yml
Labels: 🌐 Frontend

#156 [FE] hotfix fixed deploy.yml V0.0.1
  .github/workflows/deploy.yml
Labels: 🌐 Frontend

#159 [BE] fix: description varchar길이 65000에서 5000으로 수정
  src/main/resources/db/migration/V1__init.sql
Labels: 😅 Hotfix, 💯 Backend

#160 [BE] deploy v0.0.4
  src/main/resources/db/migration/V1__init.sql
Labels: 😅 Hotfix, 💯 Backend

#161 [FE] 배포 환경에서 js, css 파일 못 찾는 문제 해결
  frontend/index.html
  frontend/src/index.css
  frontend/vite.config.ts
Labels: 😅 Hotfix, 🌐 Frontend

#162 [BE] refactor: carspec 테이블명 car_spec으로 수정
  src/main/java/com/h1/mycardeepdive/options/domain/CarSpecOptions.java
  src/main/java/com/h1/mycardeepdive/options/domain/CarSpecPackage.java
  src/main/resources/db/migration/V1__init.sql
Labels: ✨ Refactor, 💯 Backend

#149 [iOS] 로딩화면 Lottie 구현
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/Resource/LoadingLottie.json
  GetYa/GetYa/Presentation/LoadingViewController.swift
Labels:  iOS, 🖥 View

#146 [iOS] 사전 질문 추가 질문 UI 구현 및 기능 구현
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/Resource/Assets.xcassets/slider-circle.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/slider-circle.imageset/slider-thumb.png
  GetYa/GetYa/App/Resource/Assets.xcassets/slider-circle.imageset/slider-thumb@2x.png
  GetYa/GetYa/App/Resource/Assets.xcassets/slider-circle.imageset/slider-thumb@3x.png
  GetYa/GetYa/Presentation/CharacterSelect/AgeViewController.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Common/BaseCharacterSelectPageViewController.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Mock/QuestionDescriptionLabelModel+Mock.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Mock/QuestionListTextModel+Mock.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Mock/QuestionSliderViewModel+Mock.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Protocol/CharacterDetailSelectViewModelabe.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Protocol/QuestionViewSendable.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/View/CharacterDetailQuestionListView.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/View/DetailQuestionCarPriceSelectView.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/View/TwoWaySlider.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewController/CharacterDetailSelectViewController.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewModel/CharacterDetailSelectViewModel.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterSelectViewController.swift
  GetYa/GetYa/Presentation/CharacterSelect/DetailLifeStyleSelectViewController.swift
  GetYa/GetYa/Presentation/CharacterSelect/LifeStyleViewController.swift
  GetYa/GetYa/Presentation/CharacterSelect/View/CheckListItemView.swift
  GetYa/GetYa/Presentation/CharacterSelect/View/CheckListStackView.swift
  GetYa/GetYa/Presentation/CharacterSelect/View/QuestionContentView.swift
  GetYa/GetYa/Presentation/Common/View/CommonLabel.swift
  GetYa/GetYa/Presentation/Common/View/CommonPaddingLabel.swift
  GetYa/GetYa/Presentation/Common/ViewController/BaseViewController.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/Adapter/CommonQuotationPreviewTableViewAdapter.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/Protocol/CommonQuotationPreviewAdapterDataSource.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/View/Header/CommonQuotationPreviewCarInfoView.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/ViewModel/CommonQuotationPreviewTableViewModel.swift
  GetYa/GetYa/Presentation/QuotationPreview/DefaultQuotationPreview/View/DefaultQuotationPreviewThumbnailCardView.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/Adapter/DetailQuotationPreviewTableViewAdapter.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/Mock/QuotationPreviewMainHeaderModel+Mock.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/Protocol/DetailQuotationPreviewAdapterDataSource.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/Protocol/DetailQuotationPreviewViewModelable.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/View/MainHeader/DetailQuotationPreviewMainHeader.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/View/MainHeader/DetailQuotationPreviewThumbnailView.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/View/TagViewCell.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/ViewController/DetailQuotationPreviewViewController.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/ViewModel/DetailQuotationPreviewViewModel.swift
  GetYa/GetYa/Presentation/QuotationPreview/QuotationFinishViewController.swift
  GetYa/GetYa/Util/Extension/Int+.swift
Labels:  iOS, 💡 Feature, 🖥 View

#165 [BE] 색상선택 API수정, 트림조회,비교 API수정
  src/main/java/com/h1/mycardeepdive/car/domain/repository/BodyRepository.java
  src/main/java/com/h1/mycardeepdive/car/domain/repository/CarSpecRepository.java
  src/main/java/com/h1/mycardeepdive/car/domain/repository/DrivingSystemRepository.java
  src/main/java/com/h1/mycardeepdive/car/domain/repository/EngineRepository.java
  src/main/java/com/h1/mycardeepdive/car/mapper/CarSpecMapper.java
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/car/ui/CarSpecController.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecComparisonResponse.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecResponse.java
  src/main/java/com/h1/mycardeepdive/color/domain/ExteriorColor.java
  src/main/java/com/h1/mycardeepdive/color/domain/InteriorColor.java
  src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimColorCombinationRepository.java
  src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimExteriorColorRepository.java
  src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimInteriorColorRepository.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/trims/domain/Trim.java
  src/main/java/com/h1/mycardeepdive/trims/domain/TrimToExterior.java
  src/main/java/com/h1/mycardeepdive/trims/domain/TrimToInterior.java
  src/test/java/com/h1/mycardeepdive/car/service/CarSpecServiceTest.java
  src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/fixture/ExteriorColorFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/InteriorColorFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/TrimFixture.java
Labels: 💯 Backend

#166 [BE] db 데이터 삽입 쿼리 작성
  src/main/resources/db/migration/V1_2__insert_data.sql
Labels: 💡 Feature, 💯 Backend

#168 hotfix: db 삽입 쿼리 중 파일 경로 수정
  src/main/resources/db/migration/V1_2__insert_data.sql
Labels: 😅 Hotfix, 💯 Backend

#169 [BE] hotfix: db 삽입 쿼리 삭제
  src/main/resources/db/migration/V1_2__insert_data.sql
Labels: 😅 Hotfix, 💯 Backend

#170 [BE] hotfix: db 삽입 쿼리 수정
  src/main/resources/db/migration/V1_2__init_insert_data.sql
Labels: 😅 Hotfix, 💯 Backend

#171 [BE] deploy v0.0.5
  src/main/java/com/h1/mycardeepdive/car/domain/repository/BodyRepository.java
  src/main/java/com/h1/mycardeepdive/car/domain/repository/CarSpecRepository.java
  src/main/java/com/h1/mycardeepdive/car/domain/repository/DrivingSystemRepository.java
  src/main/java/com/h1/mycardeepdive/car/domain/repository/EngineRepository.java
  src/main/java/com/h1/mycardeepdive/car/mapper/CarSpecMapper.java
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/car/ui/CarSpecController.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecComparisonResponse.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecResponse.java
  src/main/java/com/h1/mycardeepdive/color/domain/ExteriorColor.java
  src/main/java/com/h1/mycardeepdive/color/domain/InteriorColor.java
  src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimColorCombinationRepository.java
  src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimExteriorColorRepository.java
  src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimInteriorColorRepository.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/options/domain/CarSpecOptions.java
  src/main/java/com/h1/mycardeepdive/options/domain/CarSpecPackage.java
  src/main/java/com/h1/mycardeepdive/trims/domain/Trim.java
  src/main/java/com/h1/mycardeepdive/trims/domain/TrimToExterior.java
  src/main/java/com/h1/mycardeepdive/trims/domain/TrimToInterior.java
  src/main/resources/db/migration/V1_2__init_insert_data.sql
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/h1/mycardeepdive/car/service/CarSpecServiceTest.java
  src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/fixture/ExteriorColorFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/InteriorColorFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/TrimFixture.java
Labels: 💯 Backend

#164 [iOS] 5.1 견적서 완료 화면 구현
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/Resource/Assets.xcassets/Hyundai_Logo/Black_Logo_Title.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/Hyundai_Logo/Black_Logo_Title.imageset/Image.png
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionContentCell.swift
  GetYa/GetYa/Presentation/Home/HomeViewController.swift
  GetYa/GetYa/Presentation/QuotationFinish/CommonTableHeaderView.swift
  GetYa/GetYa/Presentation/QuotationFinish/PurchaseLearnMoreView.swift
  GetYa/GetYa/Presentation/QuotationFinish/PurchaseView.swift
  GetYa/GetYa/Presentation/QuotationFinish/QuotationFinishTableCell.swift
  GetYa/GetYa/Presentation/QuotationFinish/QuotationFinishThumbnailView.swift
  GetYa/GetYa/Presentation/QuotationFinish/QuotationFinishViewController.swift
  GetYa/GetYa/Presentation/QuotationFinish/QuotationTableView.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/View/Header/CommonQuotationPreviewCarInfoView.swift
Labels:  iOS, 🖥 View

#172 [iOS] 컨플릭트 코드 수정
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Presentation/Home/HomeViewController.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/View/Header/CommonQuotationPreviewCarInfoView.swift
  GetYa/GetYa/Presentation/QuotationPreview/QuotationFinishViewController.swift
Labels:  iOS, 🧨 Bug, 😅 Hotfix

#174 [FE] globalState 트림 적용
  frontend/src/Components/Header/Navigation/Item/index.tsx
  frontend/src/Components/Header/Navigation/index.tsx
  frontend/src/Components/Header/index.tsx
  frontend/src/Components/RadioGroup/RadioSelected/index.tsx
  frontend/src/Components/RadioGroup/RadioUnselected/index.tsx
  frontend/src/Components/RadioGroup/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/Body/Budget/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/Body/LifeStyleRadio/Selected/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/Body/LifeStyleRadio/Unselected/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/Body/LifeStyleRadio/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/Body/Title/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/Body/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/LifeStyleLink/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/NextStepButton/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/ProgressBar/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/SubTitle/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/Title/Step/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/Title/index.tsx
  frontend/src/Pages/RecommendationPage/QuestionPage/index.tsx
  frontend/src/Pages/RecommendationPage/ResultPage/index.tsx
  frontend/src/Pages/RecommendationPage/index.tsx
  frontend/src/Pages/TrimSelectionPage/Feature/FeatureRadio/Selected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Feature/FeatureRadio/Unselected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Feature/FeatureRadio/index.tsx
  frontend/src/Pages/TrimSelectionPage/ToolTip/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/Buttons/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Selected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Unselected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
  frontend/src/Pages/TrimSelectionPage/index.tsx
  frontend/src/context/CarProvider/index.tsx
  frontend/src/context/CarProvider/type.ts
  frontend/src/context/QuestionProvider/index.tsx
  frontend/src/context/QuestionProvider/type.ts
  frontend/src/global/data.ts
  frontend/src/global/type.ts
Labels: 💡 Feature, 🌐 Frontend

#176 [BE] 색상 조회 api에 트림명 추가, 변수명 수정
  src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/AllColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorInfo.java
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
Labels: 💡 Feature, 💯 Backend

#177 [iOS] common option select button 기능 업데이트
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Presentation/Common/View/CommonOptionSelectButton.swift
  GetYa/GetYa/Util/Extension/UIImage+.swift
Labels:  iOS, 🏖 Common, 💡 Feature, 🖥 View

#173 [iOS] 4.1. 옵션 선택 화면 - 카테고리 까지 구현
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/All.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/All.imageset/Image.png
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Convenience.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Convenience.imageset/Image.png
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Parking.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Parking.imageset/Image.png
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Performance.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Performance.imageset/Image.png
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/SafeDrive.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/SafeDrive.imageset/Image.png
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Style.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Style.imageset/Image.png
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Temperature.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/Temperature.imageset/Image.png
  GetYa/GetYa/Presentation/CarSettingSelect/ColorSelect/View/ColorContentView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectCategoryCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectImageCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectItemCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectSegmentedControl.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectTitleHeaderView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectViewController.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/SubOptionDetail/SubOptionDetailViewController.swift
Labels:  iOS, 🖥 View

#179 [iOS] OptionSelectCollectionView All Category Item 부분 구현
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/Resource/Assets.xcassets/ExteriorColorSelect/rotationMark.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/ExteriorColorSelect/rotationMark.imageset/Image.png
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectItemCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectItemLearnMoreView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectTitleHeaderView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectViewController.swift
  GetYa/GetYa/Presentation/Common/View/CommonOptionSelectButton.swift
Labels:  iOS, 💡 Feature, 🖥 View

#183 [FE] 색상 선택 전역 적용
  frontend/src/Components/Button/index.tsx
  frontend/src/Components/Header/Navigation/Item/index.tsx
  frontend/src/Components/Header/Navigation/index.tsx
  frontend/src/Components/Header/index.tsx
  frontend/src/Components/Header/showQuotation/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Buttons/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Explain/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/Description/index.tsx
  frontend/src/Pages/ColorSelectionPage/DropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/index.tsx
  frontend/src/context/CarProvider/index.tsx
  frontend/src/context/CarProvider/type.ts
  frontend/src/global/data.ts
  frontend/src/global/type.ts
Labels: 💡 Feature, 🌐 Frontend

#182 [FE] Error page
  frontend/src/App.tsx
  frontend/src/Components/Header/index.tsx
  frontend/src/Components/Layout/index.tsx
  frontend/src/Pages/ErrorPage/index.tsx
  frontend/src/assets/icon/error.svg
  frontend/src/hooks/useFetch.ts
  frontend/src/router/index.tsx
Labels: 💡 Feature, 🌐 Frontend

#184 [FE] React 테스트 환경 구축
  frontend/.eslintrc.cjs
  frontend/jest.config.ts
  frontend/jest.setup.ts
  frontend/package.json
  frontend/src/main.tsx
  frontend/src/test/App.test.tsx
  frontend/src/test/Wrapper/index.tsx
  frontend/src/test/mocks/fileMock.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: ✅ Test, 🌐 Frontend

#178 [BE] feat:추천 api 작성
  src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/options/domain/Packages.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/CustomRecommendation.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/Recommendation.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCar.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCarOption.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCarPackage.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/repository/CustomRecommendationRepository.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/repository/RecommendationRepository.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationOptionDtoMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/service/RecommendationService.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/RecommendationController.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationOptionDto.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/main/resources/db/migration/V1_3__init_recommendation.sql
  src/main/resources/db/migration/V1_4__init_recommendation_constraints.sql
  src/main/resources/db/migration/V1_5__init_insert_recommendation_data.sql
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
  src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/RecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
  src/test/java/com/h1/mycardeepdive/recommendation/ui/RecommendationControllerTest.java
Labels: 💡 Feature, 💯 Backend

#187 [BE] fix: 추천 관련 테이블 생성 sql 수정
  src/main/resources/db/migration/V1_3__init_recommendation.sql
Labels: 😅 Hotfix, 💯 Backend

#188 [BE] fix: 추천 관련 테이블 생성 sql 수정2
  src/main/resources/db/migration/V1_3__init_recommendation.sql
Labels: 😅 Hotfix, 💯 Backend

#189 [BE] feature/api recommendation custom
  src/main/java/com/h1/mycardeepdive/car/domain/CarSpec.java
  src/main/java/com/h1/mycardeepdive/color/domain/ExteriorColor.java
  src/main/java/com/h1/mycardeepdive/color/domain/InteriorColor.java
  src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
Labels: 💡 Feature, 💯 Backend

#190 [BE] deploy v0.0.6
  src/main/java/com/h1/mycardeepdive/car/domain/CarSpec.java
  src/main/java/com/h1/mycardeepdive/color/domain/ExteriorColor.java
  src/main/java/com/h1/mycardeepdive/color/domain/InteriorColor.java
  src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/AllColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/options/domain/Packages.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/CustomRecommendation.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/Recommendation.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCar.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCarOption.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCarPackage.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/repository/CustomRecommendationRepository.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/repository/RecommendationRepository.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationOptionDtoMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/service/RecommendationService.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/RecommendationController.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationOptionDto.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/main/resources/db/migration/V1_3__init_recommendation.sql
  src/main/resources/db/migration/V1_4__init_recommendation_constraints.sql
  src/main/resources/db/migration/V1_5__init_insert_recommendation_data.sql
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
  src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/RecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
  src/test/java/com/h1/mycardeepdive/recommendation/ui/RecommendationControllerTest.java
Labels: 💯 Backend

#194 [iOS] API 요청, 응답 시 필요한 엔티티 생성
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Domain/Entity/AdditionalOption.swift
  GetYa/GetYa/Domain/Entity/AdditionalOptionList.swift
  GetYa/GetYa/Domain/Entity/AdditionalOptionPackage.swift
  GetYa/GetYa/Domain/Entity/BasicOption.swift
  GetYa/GetYa/Domain/Entity/OptionDetail.swift
  GetYa/GetYa/Domain/Entity/PackageOptionDetail.swift
  GetYa/GetYa/Domain/Entity/Tag.swift
  GetYa/GetYa/Domain/Entity/TagDetail.swift
  GetYa/GetYa/Domain/Entity/TagOption.swift
  GetYa/GetYa/Domain/Entity/TrimOption.swift
  GetYa/GetYa/Domain/Entity/TrimSubOption.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectItemCell.swift
Labels:  iOS, 🖥 View

#195 [iOS] network end point service추가했습니다.
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/Resource/Assets.xcassets/ExteriorColorSelect/RotationMark.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/ExteriorColorSelect/RotationMark.imageset/Image.png
  GetYa/GetYa/Data/DTO/AdditionalOptionsResponseDTO.swift
  GetYa/GetYa/Data/DTO/CustomRecomendation.swift
  GetYa/GetYa/Data/DTO/DTO.swift
  GetYa/GetYa/Data/DTO/QuotationDTO.swift
  GetYa/GetYa/Data/DTO/TrimCarSpecRequestDTO.swift
  GetYa/GetYa/Data/DTO/TrimCarSpecResponseDTO.swift
  GetYa/GetYa/Data/Endpoint/OptionEndpoints.swift
  GetYa/GetYa/Data/Endpoint/RecommendationEndpoints.swift
  GetYa/GetYa/Data/Endpoint/TrimEndpoints.swift
  GetYa/GetYa/Data/Repositoy/OptionRepositoryImpl.swift
  GetYa/GetYa/Data/Repositoy/Protocol/OptionRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/RecommendationRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/TrimRepository.swift
  GetYa/GetYa/Data/Repositoy/RecommendationRepositoryImpl.swift
  GetYa/GetYa/Data/Repositoy/TrimCarSpecRepositoryImpl.swift
  GetYa/GetYa/Domain/UseCase/Protocol/CarRecommendUseCase.swift
  GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewModel/CharacterDetailSelectViewModel.swift
  GetYa/GetYa/Util/Extension/Encodable+toDictionary.swift
  GetYa/GetYa/Util/Persistence/Cache.swift
  GetYa/GetYa/Util/Persistence/Cacheable.swift
  GetYa/GetYa/Util/Persistence/DiskCache.swift
  GetYa/GetYa/Util/Persistence/MemoryCache.swift
  GetYa/GetYa/Util/Protocol/EndpointProvider.swift
  GetYa/GetYa/Util/Protocol/Requestable.swift
  GetYa/GetYa/Util/Protocol/Responsable.swift
  GetYa/GetYa/Util/Service/Endpoint.swift
  GetYa/GetYa/Util/Service/HTTPMethod.swift
  GetYa/GetYa/Util/Service/HttpStatus.swift
  GetYa/GetYa/Util/Service/NetworkError.swift
  GetYa/GetYa/Util/Service/Service.swift
  GetYa/GetYa/Util/Service/SessionProvider.swift
  GetYa/GetYa/Util/Service/Status.swift
Labels:  iOS, 🏖 Common

#193 [BE] feat: 트림, 컬러 선택 시 로그 전송 API구현
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/car/ui/CarSpecController.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/ColorController.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/test/java/com/h1/mycardeepdive/car/service/CarSpecServiceTest.java
  src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
Labels: 💡 Feature, 💯 Backend

#197 [BE] feat: pdf 생성 및 이메일 전송 기능 구현
  build.gradle
  src/main/java/com/h1/mycardeepdive/color/domain/repository/ExteriorColorRepository.java
  src/main/java/com/h1/mycardeepdive/color/domain/repository/InteriorColorRepository.java
  src/main/java/com/h1/mycardeepdive/exception/ErrorType.java
  src/main/java/com/h1/mycardeepdive/global/config/MailConfig.java
  src/main/java/com/h1/mycardeepdive/global/config/S3Config.java
  src/main/java/com/h1/mycardeepdive/global/util/B64ImgReplacedElementFactory.java
  src/main/java/com/h1/mycardeepdive/options/domain/CarSpecOptions.java
  src/main/java/com/h1/mycardeepdive/options/domain/CarSpecPackage.java
  src/main/java/com/h1/mycardeepdive/options/domain/OptionPackage.java
  src/main/java/com/h1/mycardeepdive/options/domain/repository/OptionsRepositoryImpl.java
  src/main/java/com/h1/mycardeepdive/options/mapper/OptionMapper.java
  src/main/java/com/h1/mycardeepdive/options/ui/dto/OptionDetailResponse.java
  src/main/java/com/h1/mycardeepdive/pdf/domain/PdfInfo.java
  src/main/java/com/h1/mycardeepdive/pdf/domain/repository/PdfRepository.java
  src/main/java/com/h1/mycardeepdive/pdf/service/MailService.java
  src/main/java/com/h1/mycardeepdive/pdf/service/MailServiceImpl.java
  src/main/java/com/h1/mycardeepdive/pdf/service/PdfService.java
  src/main/java/com/h1/mycardeepdive/pdf/service/S3Service.java
  src/main/java/com/h1/mycardeepdive/pdf/ui/PdfController.java
  src/main/java/com/h1/mycardeepdive/pdf/ui/dto/CarInformation.java
  src/main/java/com/h1/mycardeepdive/pdf/ui/dto/PdfIdRequest.java
  src/main/java/com/h1/mycardeepdive/pdf/ui/dto/PdfIdResponse.java
  src/main/java/com/h1/mycardeepdive/pdf/ui/dto/PdfUrlResponse.java
  src/main/java/com/h1/mycardeepdive/pdf/ui/dto/SimpleOption.java
  src/main/java/com/h1/mycardeepdive/tags/domain/OptionTag.java
  src/main/java/com/h1/mycardeepdive/tags/domain/PackageTag.java
  src/main/resources/application.yml
  src/main/resources/static/font/NanumSquareB.ttf
  src/main/resources/static/font/NanumSquareEB.ttf
  src/main/resources/static/font/NanumSquareL.ttf
  src/main/resources/static/font/NanumSquareR.ttf
  src/main/resources/static/font/NanumSquare_acB.ttf
  src/main/resources/static/font/NanumSquare_acEB.ttf
  src/main/resources/static/font/NanumSquare_acL.ttf
  src/main/resources/static/font/NanumSquare_acR.ttf
  src/main/resources/templates/template.html
  src/test/java/com/h1/mycardeepdive/color/domain/repository/ExteriorColorRepositoryTest.java
  src/test/java/com/h1/mycardeepdive/options/domain/BadgeTest.java
  src/test/java/com/h1/mycardeepdive/options/ui/OptionsControllerTest.java
  src/test/java/com/h1/mycardeepdive/pdf/domain/PdfInfoTest.java
  src/test/java/com/h1/mycardeepdive/pdf/ui/PdfControllerTest.java
  src/test/java/com/h1/mycardeepdive/tags/domain/repository/OptionTagRepositoryTest.java
Labels: 💡 Feature, 💯 Backend

#199 [BE] feat: 트림 조회 API, 추천 API 수정
  src/main/java/com/h1/mycardeepdive/car/mapper/CarSpecMapper.java
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/car/ui/CarSpecController.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecInfo.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecResponse.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationColorInfoMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationOptionInfoMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationColorInfo.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationOptionInfo.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/test/java/com/h1/mycardeepdive/car/service/CarSpecServiceTest.java
  src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
Labels: 💡 Feature, 💯 Backend

#200 [BE] feat: prometheus 설정 추가
  build.gradle
  src/main/resources/application.yml
Labels: 🏖 Common, 💯 Backend

#192 [iOS] OptionSelect Tag Item 부분 구현
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/AdditionalCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectImageCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectImageCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectItemCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectTagItemCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectTooltipView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/PlusButton.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/ViewController/OptionSelectViewController.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimTooltipView.swift
  GetYa/GetYa/Presentation/Common/View/TooltipView.swift
  GetYa/GetYa/Presentation/QuotationPreview/DefaultQuotationPreview/View/DefaultQuotationPreviewThumbnailCardView.swift
Labels:  iOS, 💡 Feature, 🖥 View

#196 [iOS] 5.1화면 기본 옵션 선택 화면 구현
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/main.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/OptionSelectCategory/main.imageset/Image.png
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/AdditionalCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/BasicCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectAdditionalItemCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectBasicItemCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectCategoryCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/ViewController/AdditionalOptionViewController.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/ViewController/BasicOptionViewController.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/ViewController/OptionSelectViewController.swift
  GetYa/GetYa/Util/Enum/TagCategoryType.swift
Labels:  iOS, 🖥 View

#203 [BE] feat: carSpecId로 같은 스펙인 carSpec들 조회 기능 구현
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/car/ui/CarSpecController.java
  src/test/java/com/h1/mycardeepdive/car/service/CarSpecServiceTest.java
  src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
Labels: 💡 Feature, 💯 Backend

#205 [BE] feat: 컬러 조회 시 채택율 내림차순으로 정렬해서 반환하는 기능 구현
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
Labels: 💡 Feature, 💯 Backend

#206 [BE] deploy v0.0.8
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/car/ui/CarSpecController.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/test/java/com/h1/mycardeepdive/car/service/CarSpecServiceTest.java
  src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
Labels: 💯 Backend

#204 [iOS] network endpoint 개선!! 공통으로 선언되는 코드 제거!!
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Data/DTO/AdditionalOptionsResponseDTO.swift
  GetYa/GetYa/Data/DTO/ColorInfoDTO.swift
  GetYa/GetYa/Data/DTO/CommonDTO.swift
  GetYa/GetYa/Data/DTO/OptionInfoDTO.swift
  GetYa/GetYa/Data/DTO/PackageInfoDTO.swift
  GetYa/GetYa/Data/DTO/QuotationDTO.swift
  GetYa/GetYa/Data/DTO/TrimCarSpec.swift
  GetYa/GetYa/Data/DTO/TrimCarSpecResponseDTO.swift
  GetYa/GetYa/Data/Endpoint/OptionEndpoints.swift
  GetYa/GetYa/Data/Endpoint/QuotationEndpoints.swift
  GetYa/GetYa/Data/Endpoint/TrimEndpoints.swift
  GetYa/GetYa/Data/Repositoy/DefaultQuotationRepository.swift
  GetYa/GetYa/Data/Repositoy/OptionRepositoryImpl.swift
  GetYa/GetYa/Data/Repositoy/Protocol/OptionRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/QuotationRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/RecommendationRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/TrimRepository.swift
  GetYa/GetYa/Data/Repositoy/TrimCarSpecRepositoryImpl.swift
  GetYa/GetYa/Util/Protocol/EndpointProvider.swift
  GetYa/GetYa/Util/Protocol/Requestable.swift
  GetYa/GetYa/Util/Service/Endpoint.swift
  GetYa/GetYa/Util/Service/HttpStatus.swift
  GetYa/GetYa/Util/Service/NetworkError.swift
  GetYa/GetYa/Util/Service/SessionProvider.swift
Labels:  iOS, 🏖 Common, ✨ Enhancement, 💡 Feature

#207 [iOS] 2.1 화면 ViewModel, UseCase 생성 및 바인딩
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Domain/Entity/CarSettingSelectModel.swift
  GetYa/GetYa/Domain/Entity/ColorSelectModel.swift
  GetYa/GetYa/Domain/Entity/OptionSelectModel.swift
  GetYa/GetYa/Domain/Entity/TrimSelectModel.swift
  GetYa/GetYa/Domain/Entity/TrimSubOption.swift
  GetYa/GetYa/Domain/Entity/TrimSubOptionSelectModel.swift
  GetYa/GetYa/Domain/UseCase/DefaultCarSettingUseCase.swift
  GetYa/GetYa/Domain/UseCase/Protocol/ColorSelectUseCase.swift
  GetYa/GetYa/Domain/UseCase/Protocol/OptionSelectUseCase.swift
  GetYa/GetYa/Domain/UseCase/Protocol/TrimSelectUseCase.swift
  GetYa/GetYa/Presentation/CarSettingSelect/CarSettingSelect/ViewController/CarSettingSelectViewController.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionContentCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionContentCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimSubOptionContentStackView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimSubOptionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/ViewController/TrimSelectViewController.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/ViewModel/TrimSelectViewModel.swift
  GetYa/GetYa/Presentation/Home/ViewController/HomeViewController.swift
  GetYa/GetYa/Util/Extension/String+.swift
Labels:  iOS, 💡 Feature

#212 [BE] feat: 추천, 트림, 컬러 API수정
  src/main/java/com/h1/mycardeepdive/car/mapper/CarSpecMapper.java
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecInfo.java
  src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/ColorController.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/AllColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
Labels: 💡 Feature, 💯 Backend

#213 [BE] feat: 트림, 컬러 반환 API 수정
  scripts-dev/pull-and-run-container-dev.sh
  scripts-prod/pull-and-run-container-prod.sh
  src/main/java/com/h1/mycardeepdive/car/mapper/CarSpecMapper.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecInfo.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecResponse.java
  src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ColorInfo.java
Labels: 💡 Feature, 💯 Backend

#214 [BE] deploy v0.0.9
  scripts-dev/pull-and-run-container-dev.sh
  scripts-prod/pull-and-run-container-prod.sh
  src/main/java/com/h1/mycardeepdive/car/mapper/CarSpecMapper.java
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecInfo.java
  src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecResponse.java
  src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/color/ui/ColorController.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/AllColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ColorResponse.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java
  src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
  src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
Labels: 💯 Backend

#215 [BE] feat: 로그를 파일로 저장
  build.gradle
  src/main/java/com/h1/mycardeepdive/global/scheduler/LogCleanupScheduler.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationOptionInfo.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/main/resources/logback-spring.xml
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
Labels: 💯 Backend

#208 [FE] 옵션 API 연결
  frontend/src/Components/Header/HeaderLogo/index.tsx
  frontend/src/Components/Header/Navigation/index.tsx
  frontend/src/Components/Header/OptionItem/index.tsx
  frontend/src/Components/Header/index.tsx
  frontend/src/Components/Loading/index.tsx
  frontend/src/Components/Modal/index.tsx
  frontend/src/Pages/MyCarResultPage/Head/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/SelectedButton/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/UnSelectedButton/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/index.tsx
  frontend/src/Pages/OptionSelectitonPage/BasicOption/Option/index.tsx
  frontend/src/Pages/OptionSelectitonPage/BasicOption/index.tsx
  frontend/src/Pages/OptionSelectitonPage/BottomButtons/index.tsx
  frontend/src/Pages/OptionSelectitonPage/OptionModal/OptionCard/index.tsx
  frontend/src/Pages/OptionSelectitonPage/OptionModal/index.tsx
  frontend/src/Pages/OptionSelectitonPage/Pagination/index.tsx
  frontend/src/Pages/OptionSelectitonPage/SituationOption/OptionInfo/index.tsx
  frontend/src/Pages/OptionSelectitonPage/SituationOption/OptionList/Option/index.tsx
  frontend/src/Pages/OptionSelectitonPage/SituationOption/OptionList/index.tsx
  frontend/src/Pages/OptionSelectitonPage/SituationOption/index.tsx
  frontend/src/Pages/OptionSelectitonPage/Tag/TagButton/index.tsx
  frontend/src/Pages/OptionSelectitonPage/Tag/index.tsx
  frontend/src/Pages/OptionSelectitonPage/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
  frontend/src/Pages/TrimSelectionPage/index.tsx
  frontend/src/api/option/getAdditionalOptions.tsx
  frontend/src/api/option/getBasicOptions.tsx
  frontend/src/api/option/getOptionDetails.tsx
  frontend/src/api/option/getPackageOptionDetails.tsx
  frontend/src/api/option/getSituationOptions.tsx
  frontend/src/api/trim/getTrim.tsx
  frontend/src/assets/image/Loading_Car.gif
  frontend/src/context/CarProvider/index.tsx
  frontend/src/context/CarProvider/type.ts
  frontend/src/context/OptionProvider/index.tsx
  frontend/src/context/OptionProvider/type.ts
  frontend/src/global/type.ts
  frontend/src/hooks/useFetch.ts
  frontend/src/main.tsx
  frontend/src/utils/index.ts
Labels: 💡 Feature, 🌐 Frontend

#217 [FE] color API 연결
  frontend/src/Components/CarRotation/index.tsx
  frontend/src/Components/ControlButtons/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Buttons/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Button/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Icon/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Image/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Items/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Tag/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/TrimName/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/DropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/index.tsx
  frontend/src/Pages/TrimSelectionPage/Car/ControlButtons/index.tsx
  frontend/src/Pages/TrimSelectionPage/index.tsx
  frontend/src/api/color/getAllColor.tsx
  frontend/src/api/color/getExteriorColor.tsx
  frontend/src/api/color/getInitialExteriorColor.tsx
  frontend/src/api/color/getInitialInteriorColor.tsx
  frontend/src/api/color/getInteriorColors.tsx
  frontend/src/global/data.ts
  frontend/src/global/type.ts
  frontend/src/hooks/useInitialColor.ts
Labels: 💡 Feature, 🌐 Frontend

#219 [BE] feat: activity-log요청에 로그 출력
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/resources/logback-spring.xml
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
Labels: 💡 Feature, 💯 Backend

#220 [BE] deploy v0.1.0
  build.gradle
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/global/scheduler/LogCleanupScheduler.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationOptionInfo.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/main/resources/logback-spring.xml
  src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
Labels: 💯 Backend

#222 [iOS] 5.1 견적 완료 화면 데이터 받기, 이메일 보내기 API 연결
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/Info.plist
  GetYa/GetYa/App/Resource/Assets.xcassets/quotationfinishCar.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/quotationfinishCar.imageset/Image.png
  GetYa/GetYa/App/Resource/Assets.xcassets/share.imageset/Contents.json
  GetYa/GetYa/App/Resource/Assets.xcassets/share.imageset/Image.png
  GetYa/GetYa/Data/DTO/OptionInfoDTO.swift
  GetYa/GetYa/Data/DTO/QuotationFinishDTO.swift
  GetYa/GetYa/Data/Endpoint/QuotationFinishEndpoint.swift
  GetYa/GetYa/Data/Repositoy/DefaultQuotationFinishRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/QuotationFinishRepository.swift
  GetYa/GetYa/Domain/Entity/OptionInfo.swift
  GetYa/GetYa/Domain/Entity/PdfEmail.swift
  GetYa/GetYa/Domain/Entity/QuotationFinish.swift
  GetYa/GetYa/Domain/UseCase/DefaultQuotationFinishUseCase.swift
  GetYa/GetYa/Domain/UseCase/Protocol/QuotationFinishUseCase.swift
  GetYa/GetYa/Presentation/Common/View/CommonOptionView.swift
  GetYa/GetYa/Presentation/Common/View/OptionNameAndPriceView.swift
  GetYa/GetYa/Presentation/Common/ViewController/AlertViewController.swift
  GetYa/GetYa/Presentation/Common/ViewController/LoadingViewController.swift
  GetYa/GetYa/Presentation/QuotationFinish/View/QuotationFinishTableCell.swift
  GetYa/GetYa/Presentation/QuotationFinish/View/QuotationFinishThumbnailView.swift
  GetYa/GetYa/Presentation/QuotationFinish/View/QuotationTableView.swift
  GetYa/GetYa/Presentation/QuotationFinish/ViewController/QuotationFinishViewController.swift
  GetYa/GetYa/Presentation/QuotationFinish/ViewModel/QuotaionFinishViewModel.swift
  GetYa/GetYa/Presentation/QuotationFinish/ViewModel/QuotationFinishViewModel.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/View/CommonQuotationPreviewCell.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/View/Header/CommonQuotationPreviewCarInfoView.swift
  GetYa/GetYa/Presentation/QuotationPreview/CommonQuotationPreview/ViewModel/CommonQuotationPreviewTableViewModel.swift
  GetYa/GetYa/Util/Enum/AlertType.swift
  GetYa/GetYa/Util/Extension/UIImage+.swift
  GetYa/GetYa/Util/Extension/UIImageView+.swift
  GetYa/GetYa/Util/Extension/UIViewController+.swift
  GetYa/GetYa/Util/Persistence/DefaultGetYaCacheService.swift
  GetYa/GetYa/Util/Persistence/DiskCache.swift
  GetYa/GetYa/Util/Protocol/Responsable.swift
Labels:  iOS, 💡 Feature

#223 [iOS] network endpoint bodyParam 추가했습니다.
  GetYa/GetYa/Util/Protocol/Requestable.swift
  GetYa/GetYa/Util/Service/Endpoint.swift
  GetYa/GetYa/Util/Service/SessionProvider.swift
Labels:  iOS, 🏖 Common

#225 [BE] deploy v0.1.1
  src/main/java/com/h1/mycardeepdive/recommendation/domain/Recommendation.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCar.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/service/RecommendationService.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/main/resources/db/migration/V1_3__init_recommendation.sql
  src/main/resources/db/migration/V1_5__init_insert_recommendation_data.sql
  src/main/resources/db/migration/V1_6__init_delete_wrong_data.sql
  src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/RecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
Labels: 💯 Backend

#226 [BE] deploy v0.1.1
  src/main/java/com/h1/mycardeepdive/recommendation/domain/Recommendation.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCar.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/service/RecommendationService.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java
  src/main/resources/db/migration/V1_3__init_recommendation.sql
  src/main/resources/db/migration/V1_5__init_insert_recommendation_data.sql
  src/main/resources/db/migration/V1_6__init_delete_wrong_data.sql
  src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/RecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
Labels: 💯 Backend

#227 [FE] 색상 API 연결, 로직 수정
  frontend/src/Components/CarRotation/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Buttons/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/DropDown/DropDownButton/index.tsx
  frontend/src/Pages/ColorSelectionPage/DropDown/DropDownContent/index.tsx
  frontend/src/Pages/ColorSelectionPage/DropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorImg/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/OtherExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/OtherInteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/index.tsx
  frontend/src/api/color/getExteriorColor.tsx
  frontend/src/api/color/getInitialExteriorColor.tsx
  frontend/src/api/color/getInitialInteriorColor.tsx
  frontend/src/api/color/getInteriorColors.tsx
  frontend/src/api/trim/getTrim.tsx
  frontend/src/assets/icon/exclamation.png
  frontend/src/context/CarProvider/index.tsx
  frontend/src/global/type.ts
  frontend/src/hooks/useInitialColor.ts
Labels: 💡 Feature, 🌐 Frontend

#229 [FE] 로그 API 연결
  frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/index.tsx
  frontend/src/Pages/OptionSelectitonPage/OptionModal/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Selected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Unselected/index.tsx
  frontend/src/context/CarProvider/index.tsx
  frontend/src/context/OptionProvider/index.tsx
  frontend/src/context/QuestionProvider/index.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/hooks/useLogFetch.ts
Labels: 🌐 Frontend

#224 [iOS] 5.1 화면, 로딩화면 API 모두 연결
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/App/SceneDelegate.swift
  GetYa/GetYa/Data/DTO/ContractionQuotationDTO.swift
  GetYa/GetYa/Data/DTO/PdfIdDTO.swift
  GetYa/GetYa/Data/DTO/PdfUrlDTO.swift
  GetYa/GetYa/Data/Endpoint/LoadingEndpoint.swift
  GetYa/GetYa/Data/Endpoint/QuotationFinishEndpoint.swift
  GetYa/GetYa/Data/Repositoy/DefaultLoadingRepository.swift
  GetYa/GetYa/Data/Repositoy/DefaultQuotationFinishRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/LoadingRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/QuotationFinishRepository.swift
  GetYa/GetYa/Domain/Entity/ContractionQuotation.swift
  GetYa/GetYa/Domain/Entity/Entity.swift
  GetYa/GetYa/Domain/Entity/TrimSubOptionSelectModel.swift
  GetYa/GetYa/Domain/UseCase/DefaultLoadingUseCase.swift
  GetYa/GetYa/Domain/UseCase/DefaultQuotationFinishUseCase.swift
  GetYa/GetYa/Domain/UseCase/Protocol/LoadingUseCase.swift
  GetYa/GetYa/Domain/UseCase/Protocol/QuotationFinishUseCase.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/ViewController/OptionSelectViewController.swift
  GetYa/GetYa/Presentation/Common/Model/MyActivityItemSource.swift
  GetYa/GetYa/Presentation/Loading/ViewController/LoadingViewController.swift
  GetYa/GetYa/Presentation/Loading/ViewModel/LoadingViewModel.swift
  GetYa/GetYa/Presentation/QuotationFinish/ViewController/QuotationFinishViewController.swift
  GetYa/GetYa/Presentation/QuotationFinish/ViewModel/QuotationFinishViewModel.swift
  GetYa/GetYa/Presentation/QuotationPreview/DefaultQuotationPreview/DefaultQuotationPreviewViewController.swift
  GetYa/GetYa/Presentation/QuotationPreview/DetailQuotationPreview/ViewController/DetailQuotationPreviewViewController.swift
  GetYa/GetYa/Util/Extension/UIViewController+.swift
  GetYa/GetYa/Util/Protocol/Responsable.swift
Labels:  iOS, 🖥 View

#232 [BE] refactor: Option, OptionTag api 최적화
  src/main/java/com/h1/mycardeepdive/exception/ErrorType.java
  src/main/java/com/h1/mycardeepdive/options/domain/repository/OptionsRepositoryCustom.java
  src/main/java/com/h1/mycardeepdive/options/domain/repository/OptionsRepositoryImpl.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/java/com/h1/mycardeepdive/pdf/service/PdfService.java
  src/main/java/com/h1/mycardeepdive/tags/domain/repository/OptionTagRepository.java
  src/main/java/com/h1/mycardeepdive/tags/domain/repository/OptionTagRepositoryCustom.java
  src/main/java/com/h1/mycardeepdive/tags/domain/repository/OptionTagRepositoryImpl.java
Labels: ✨ Refactor, 💯 Backend

#233 [BE] deploy v0.1.2
  src/main/java/com/h1/mycardeepdive/exception/ErrorType.java
  src/main/java/com/h1/mycardeepdive/options/domain/repository/OptionsRepositoryCustom.java
  src/main/java/com/h1/mycardeepdive/options/domain/repository/OptionsRepositoryImpl.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/java/com/h1/mycardeepdive/pdf/service/PdfService.java
  src/main/java/com/h1/mycardeepdive/tags/domain/repository/OptionTagRepository.java
  src/main/java/com/h1/mycardeepdive/tags/domain/repository/OptionTagRepositoryCustom.java
  src/main/java/com/h1/mycardeepdive/tags/domain/repository/OptionTagRepositoryImpl.java
Labels: ✨ Refactor, 💯 Backend

#238 [FE] 최적화 수정
  frontend/src/api/Recommendation/getCustomRecommendation.tsx
  frontend/src/api/Recommendation/getRecommendation.tsx
  frontend/src/api/color/getAllColor.tsx
  frontend/src/api/color/getExteriorColor.tsx
  frontend/src/api/myCar/getMyCarResult.tsx
  frontend/src/api/myCar/postResult.tsx
  frontend/src/api/option/getAdditionalOptions.tsx
  frontend/src/api/option/getBasicOptions.tsx
  frontend/src/api/option/getOptionDetails.tsx
  frontend/src/api/option/getPackageOptionDetails.tsx
  frontend/src/api/option/getSituationOptions.tsx
  frontend/src/api/trim/getComparison.tsx
  frontend/src/api/trim/getTrim.tsx
  frontend/src/hooks/useFetch.ts
Labels: 😅 Hotfix, 🌐 Frontend

#235 [iOS] 트림 선택 화면 API 연결
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Data/DTO/TrimCarSpec.swift
  GetYa/GetYa/Data/DTO/TrimCarSpecDTO.swift
  GetYa/GetYa/Data/DTO/TrimInqueryDTO.swift
  GetYa/GetYa/Data/DTO/TrimSubOptionSelectDTO.swift
  GetYa/GetYa/Data/Endpoint/TrimSelectEndpoint.swift
  GetYa/GetYa/Data/Repositoy/DefaultTrimSelectRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/TrimSelectRepository.swift
  GetYa/GetYa/Domain/Entity/TrimCarSpec.swift
  GetYa/GetYa/Domain/Entity/TrimInquery.swift
  GetYa/GetYa/Domain/Entity/TrimSelectModel.swift
  GetYa/GetYa/Domain/Entity/TrimSubOptionSelect.swift
  GetYa/GetYa/Domain/UseCase/DefaultCarSettingUseCase.swift
  GetYa/GetYa/Domain/UseCase/Protocol/TrimSelectUseCase.swift
  GetYa/GetYa/Presentation/CarSettingSelect/CarSettingSelect/ViewController/CarSettingSelectViewController.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimHeaderView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionContentCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionContentCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionDetailColorCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionDetailColorCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionDetailOptionCell.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionDetailOptionCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/View/TrimOptionDetailView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/ViewController/TrimSelectViewController.swift
  GetYa/GetYa/Presentation/CarSettingSelect/TrimSelect/ViewModel/TrimSelectViewModel.swift
  GetYa/GetYa/Presentation/Common/View/CommonButton.swift
  GetYa/GetYa/Presentation/Home/View/HomeContentView.swift
  GetYa/GetYa/Presentation/Home/ViewController/HomeViewController.swift
  GetYa/GetYa/Presentation/QuotationFinish/ViewController/QuotationFinishViewController.swift
  GetYa/GetYa/Util/Enum/TrimSubOptionType.swift
  GetYa/GetYa/Util/Protocol/Responsable.swift
Labels:  iOS, 🖥 View

#240 [FE] 차량 z 인덱스 수정
  frontend/src/Components/CarRotation/index.tsx
  frontend/src/Pages/ColorSelectionPage/ContentsWrapper/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx
  frontend/src/Pages/TrimSelectionPage/FeatureAndTrimSelectionWrapper/index.tsx
  frontend/src/context/CarProvider/index.tsx
Labels: 😅 Hotfix, 🌐 Frontend

#237 [BE] feat: 최대예산 반영 로직 구현
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/CustomRecommendation.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/CustomRecommendationCar.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/service/RecommendationService.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/RecommendationController.java
  src/main/resources/db/migration/V1_2__init_insert_data.sql
  src/main/resources/db/migration/V1_3__init_recommendation.sql
  src/main/resources/db/migration/V1_4__init_recommendation_constraints.sql
  src/main/resources/db/migration/V1_5__init_insert_recommendation_data.sql
  src/main/resources/db/migration/V1_7__init_update_comments.sql
  src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationCarFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
  src/test/java/com/h1/mycardeepdive/recommendation/ui/RecommendationControllerTest.java
Labels: 💡 Feature, 💯 Backend

#245 [FE] 로그 API, 기본 옵션 수정
  frontend/src/Components/CarRotation/index.tsx
  frontend/src/Pages/OptionSelectitonPage/BasicOption/index.tsx
  frontend/src/Pages/OptionSelectitonPage/index.tsx
  frontend/src/api/option/getBasicOptions.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/hooks/useLogFetch.ts
Labels: 😅 Hotfix, 🌐 Frontend

#246 [FE] 느낌표 크기 줄이기
  frontend/src/Pages/ColorSelectionPage/ColorItems/Icon/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
Labels: 🌐 Frontend, 🖌 Design

#247 [FE] deploy v1.0.1
  frontend/src/Components/CarRotation/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Icon/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
  frontend/src/Pages/OptionSelectitonPage/BasicOption/index.tsx
  frontend/src/Pages/OptionSelectitonPage/index.tsx
  frontend/src/api/option/getBasicOptions.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/hooks/useLogFetch.ts
Labels: 🌐 Frontend

#248 [BE] deploy v0.1.3
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/CustomRecommendation.java
  src/main/java/com/h1/mycardeepdive/recommendation/domain/CustomRecommendationCar.java
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
  src/main/java/com/h1/mycardeepdive/recommendation/service/RecommendationService.java
  src/main/java/com/h1/mycardeepdive/recommendation/ui/RecommendationController.java
  src/main/resources/db/migration/V1_2__init_insert_data.sql
  src/main/resources/db/migration/V1_3__init_recommendation.sql
  src/main/resources/db/migration/V1_4__init_recommendation_constraints.sql
  src/main/resources/db/migration/V1_5__init_insert_recommendation_data.sql
  src/main/resources/db/migration/V1_7__init_update_comments.sql
  src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationCarFixture.java
  src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationFixture.java
  src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
  src/test/java/com/h1/mycardeepdive/recommendation/ui/RecommendationControllerTest.java
Labels: 💯 Backend

#249 [BE] fix: 트림id로 모든 컬러 조회 시 내장, 외장 매치 안되는 것 수정
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
Labels: 💯 Backend

#255 [BE] feat: PDF 생성 실패 시, catch 에러 추가
  src/main/java/com/h1/mycardeepdive/exception/ErrorType.java
  src/main/java/com/h1/mycardeepdive/global/config/WebConfiguration.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/java/com/h1/mycardeepdive/pdf/service/MailServiceImpl.java
Labels: 💡 Feature, 💯 Backend

#256 [BE] refactor: PDF/메일 도메인 리팩토링
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java
  src/main/java/com/h1/mycardeepdive/pdf/service/MailService.java
  src/main/java/com/h1/mycardeepdive/pdf/service/MailServiceImpl.java
  src/main/java/com/h1/mycardeepdive/pdf/service/PdfService.java
  src/main/java/com/h1/mycardeepdive/pdf/service/S3Service.java
  src/main/java/com/h1/mycardeepdive/pdf/ui/PdfController.java
  src/test/java/com/h1/mycardeepdive/pdf/service/MailServiceImplTest.java
  src/test/java/com/h1/mycardeepdive/pdf/ui/PdfControllerTest.java
Labels: ✨ Refactor, 💯 Backend

#251 [FE] 변경 모달 정보 반영
  frontend/src/Pages/ColorSelectionPage/ChangerModal/ChangePrice/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/ChangeTrim/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/CurrentTrim/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx
  frontend/src/Pages/RecommendationPage/ResultPage/Buttons/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/Buttons/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/ModalContentsWrapper/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/UnlockColor/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/UnlockItem/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/UnlockOption/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/index.tsx
  frontend/src/context/CarProvider/index.tsx
  frontend/src/context/CarProvider/type.ts
Labels: 💡 Feature, 🌐 Frontend

#257 [FE] 호환 불가능한 색 느낌표 위치 옮기기
  frontend/src/Pages/ColorSelectionPage/ColorItems/Icon/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Image/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/index.tsx
Labels: 😅 Hotfix, 🌐 Frontend

#259 [FE] 버그와 빠진 내용 수정
  frontend/src/Components/Header/showQuotation/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/SelectedButton/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/UnSelectedButton/index.tsx
  frontend/src/Pages/RecommendationPage/ResultPage/Buttons/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/Buttons/index.tsx
  frontend/src/context/CarProvider/index.tsx
  frontend/src/context/CarProvider/type.ts
Labels: 🧨 Bug, 💡 Feature, 🌐 Frontend

#263 [FE] 호환 불가능 색상 선택시 모달 띄우기
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Explain/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Title/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/UnavailableChangerModal/index.tsx
Labels: 💡 Feature, 🌐 Frontend, 🖌 Design

#265 [FE] 누락된 데이터 정리
  frontend/index.html
  frontend/public/favicon.ico
  frontend/public/vite.svg
  frontend/src/Components/Header/showQuotation/index.tsx
  frontend/src/Pages/MyCarResultPage/BottomButtons/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/index.tsx
  frontend/src/Pages/OptionSelectitonPage/OptionModal/OptionCard/index.tsx
  frontend/src/Pages/OptionSelectitonPage/SituationOption/OptionList/Option/index.tsx
  frontend/src/Pages/TrimSelectionPage/Feature/InformationModal/Item/index.tsx
  frontend/src/Pages/TrimSelectionPage/Feature/InformationModal/index.tsx
  frontend/src/Pages/TrimSelectionPage/OptionToolTip/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Selected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Unselected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
  frontend/src/Pages/TrimSelectionPage/index.tsx
  frontend/src/assets/image/body7.jpeg
  frontend/src/assets/image/body8.jpeg
  frontend/src/assets/image/wd2.jpeg
  frontend/src/assets/image/wd4.jpeg
  frontend/src/global/data.ts
Labels: 💡 Feature, 😅 Hotfix, 🌐 Frontend

#266 [FE] 트림 변경 시 기본 이미지 설정
  frontend/src/Components/CarRotation/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/Buttons/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Selected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Unselected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
  frontend/src/Pages/TrimSelectionPage/index.tsx
  frontend/src/api/trim/getTrim.tsx
Labels: 💡 Feature, 🌐 Frontend

#267 [FE] 토스트 애니메이션 수정
  frontend/src/Components/Toast/index.tsx
Labels: 🧨 Bug, 😅 Hotfix

#269 [FE] 내장 클릭 시 내장 이미지 띄우기
  frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
Labels: 💡 Feature, 🌐 Frontend

#271 [BE] refactor: 로그백 및 배치잡 설정
  build.gradle
  src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java
  src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java
  src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
  src/main/java/com/h1/mycardeepdive/exception/ErrorType.java
  src/main/java/com/h1/mycardeepdive/global/config/DocumentCleanupJobConfig.java
  src/main/java/com/h1/mycardeepdive/global/config/SchedulerConfig.java
  src/main/java/com/h1/mycardeepdive/global/scheduler/LogCleanupScheduler.java
  src/main/java/com/h1/mycardeepdive/pdf/domain/PdfInfo.java
  src/main/java/com/h1/mycardeepdive/pdf/domain/repository/PdfRepository.java
  src/main/java/com/h1/mycardeepdive/pdf/service/PdfService.java
  src/main/java/com/h1/mycardeepdive/recommendation/service/RecommendationService.java
  src/test/java/com/h1/mycardeepdive/pdf/domain/PdfInfoTest.java
Labels: 💡 Feature, ✨ Refactor, 💯 Backend

#273 [FE] 약간의 버그들
  frontend/src/Components/Toast/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/CompareModal/Trim/BasicOption/BasicOptionItem/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/CompareModal/Trim/BasicOption/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
Labels: 😅 Hotfix, 🌐 Frontend

#274 [FE] deploy v1.2.0
  frontend/index.html
  frontend/public/favicon.ico
  frontend/public/vite.svg
  frontend/src/Components/CarRotation/index.tsx
  frontend/src/Components/Header/showQuotation/index.tsx
  frontend/src/Components/Toast/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/ChangePrice/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/ChangeTrim/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/CurrentTrim/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Explain/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/Title/index.tsx
  frontend/src/Pages/ColorSelectionPage/ChangerModal/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Icon/index.tsx
  frontend/src/Pages/ColorSelectionPage/ColorItems/Image/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx
  frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
  frontend/src/Pages/ColorSelectionPage/UnavailableChangerModal/index.tsx
  frontend/src/Pages/ColorSelectionPage/index.tsx
  frontend/src/Pages/MyCarResultPage/BottomButtons/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/SelectedButton/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/UnSelectedButton/index.tsx
  frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/index.tsx
  frontend/src/Pages/OptionSelectitonPage/OptionModal/OptionCard/index.tsx
  frontend/src/Pages/OptionSelectitonPage/SituationOption/OptionList/Option/index.tsx
  frontend/src/Pages/RecommendationPage/ResultPage/Buttons/index.tsx
  frontend/src/Pages/TrimSelectionPage/Feature/InformationModal/Item/index.tsx
  frontend/src/Pages/TrimSelectionPage/Feature/InformationModal/index.tsx
  frontend/src/Pages/TrimSelectionPage/OptionToolTip/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/Buttons/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/ModalContentsWrapper/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/UnlockColor/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/UnlockItem/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/UnlockOption/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/CompareModal/Trim/BasicOption/BasicOptionItem/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/CompareModal/Trim/BasicOption/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Selected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/Unselected/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
  frontend/src/Pages/TrimSelectionPage/index.tsx
  frontend/src/api/trim/getTrim.tsx
  frontend/src/assets/image/body7.jpeg
  frontend/src/assets/image/body8.jpeg
  frontend/src/assets/image/wd2.jpeg
  frontend/src/assets/image/wd4.jpeg
  frontend/src/context/CarProvider/index.tsx
  frontend/src/context/CarProvider/type.ts
  frontend/src/global/data.ts
Labels: 🌐 Frontend

#276 [BE] fix: 추천에서 패키지 반환하지 않게 수정
  src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
Labels: 💯 Backend

#277 [FE] 데이터 캐싱 시간 변경
  frontend/src/context/CacheProvider/index.tsx
Labels: 😅 Hotfix, 🌐 Frontend

#278 [FE] deploy v1.2.1
  frontend/src/context/CacheProvider/index.tsx
Labels: 🌐 Frontend

#279 [BE] fix: 내장, 외장 가격 색상 총 가격에 반영
  src/main/java/com/h1/mycardeepdive/pdf/service/PdfService.java
Labels: 🧨 Bug, 💯 Backend

#280 [FE] 트림 라디오 키 수정
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
Labels: 😅 Hotfix, 🌐 Frontend

#282 [FE] 스크롤 버그
  frontend/src/Pages/TrimSelectionPage/Feature/InformationModal/index.tsx
Labels: 😅 Hotfix, 🌐 Frontend

#283 [FE] deploy v1.2.2
  frontend/src/Pages/TrimSelectionPage/Feature/InformationModal/index.tsx
  frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
Labels: 🌐 Frontend

#284 [iOS] 파일 정리했습니다.
  GetYa/GetYa.xcodeproj/project.pbxproj
  GetYa/GetYa/Data/DTO/CustomRecomendationDTO.swift
  GetYa/GetYa/Data/DTO/TrimID.swift
  GetYa/GetYa/Data/DTO/TrimIdDTO.swift
  GetYa/GetYa/Data/Endpoint/ColorSelectEndpoint.swift
  GetYa/GetYa/Data/Endpoint/QuotationEndpoint.swift
  GetYa/GetYa/Data/Repositoy/DefaultQuotationRepository.swift
  GetYa/GetYa/Data/Repositoy/Protocol/QuotationRepository.swift
  GetYa/GetYa/Domain/Entity/AdditionalOption.swift
  GetYa/GetYa/Domain/Entity/CustomRecomendationModel.swift
  GetYa/GetYa/Domain/Entity/DefaultTrimCarSpec.swift
  GetYa/GetYa/Domain/UseCase/Protocol/DefaultRecommendQuotationUseCase.swift
  GetYa/GetYa/Domain/UseCase/RecommendQuotationUseCase.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/AdditionalCollectionView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/View/OptionSelectTitleHeaderView.swift
  GetYa/GetYa/Presentation/CarSettingSelect/SettingSelect/ViewController/CarSettingSelectViewController.swift
  GetYa/GetYa/Presentation/CharacterSelect/View/CheckListStackView.swift
  GetYa/GetYa/Presentation/CharacterSelect/View/LifeStylePeekContentView.swift
  GetYa/GetYa/Presentation/CharacterSelect/ViewController/LifeStylePeekViewController.swift
  GetYa/GetYa/Presentation/CharacterSelect/ViewController/LifeStyleViewController.swift
  GetYa/GetYa/Presentation/Common/View/CommonTextView.swift
  GetYa/GetYa/Presentation/Common/View/CommonView.swift
  GetYa/GetYa/Presentation/Common/ViewModel/CommonViewModel.swift
  GetYa/GetYa/Presentation/Coordinator/PresentationCoordinator.swift
  GetYa/GetYa/Presentation/QuotationPreview/Adapter/CommonQuotationPreviewTableViewAdapter.swift
  GetYa/GetYa/Presentation/QuotationPreview/Adapter/DetailQuotationPreviewTableViewAdapter.swift
  GetYa/GetYa/Presentation/QuotationPreview/DefaultQuotationPreview/DefaultQuotationPreviewViewController.swift
  GetYa/GetYa/Presentation/QuotationPreview/Protocol/CommonQuotationPreviewAdapterDataSource.swift
  GetYa/GetYa/Presentation/QuotationPreview/Protocol/DetailQuotationPreviewAdapterDataSource.swift
  GetYa/GetYa/Presentation/QuotationPreview/Protocol/DetailQuotationPreviewViewModelable.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/CommonQuotationPreviewCarInfoView.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/CommonQuotationPreviewCell.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/CommonQuotationPreviewTableView.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/CommonQuotationPreviewTitleView.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/CustomOrQuoteSelectView.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/DetailQuotationPreviewFooterView.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/DetailQuotationPreviewMainHeader.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/DetailQuotationPreviewSecionHeaderView.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/DetailQuotationPreviewTableView.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/DetailQuotationPreviewThumbnailView.swift
  GetYa/GetYa/Presentation/QuotationPreview/View/TagViewCell.swift
  GetYa/GetYa/Presentation/QuotationPreview/ViewController/DetailQuotationPreviewViewController.swift
  GetYa/GetYa/Presentation/QuotationPreview/ViewController/RecommendQuotationViewController.swift
  GetYa/GetYa/Presentation/QuotationPreview/ViewModel/CommonQuotationPreviewTableViewModel.swift
  GetYa/GetYa/Presentation/QuotationPreview/ViewModel/DetailQuotationPreviewViewModel.swift
  GetYa/GetYa/Util/Enum/QuotationPreviewHeaderTitleList.swift
  GetYa/GetYa/Util/Etc/Etc.swift
  GetYa/GetYa/Util/Extension/UIViewController+.swift
  GetYa/GetYa/Util/Protocol/Responsable.swift
Labels:  iOS, 🏖 Common
